# fly.toml app configuration file for CapitalPay Bot

app = "capitalpay-bot"
primary_region = "waw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1024"
  cpu_kind = "shared"
  cpus = 1

[experimental]
  auto_rollback = true

[processes]
  app = "python bot.py"


